services:
  # Backend API
  - type: web
    name: video-portfolio-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_ENDPOINT
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend
  - type: web
    name: video-portfolio-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production 